### ISSUE TITLE
cross platform build issue

### ISSUE THREAD

**Issue by zhoumingmtv** [openark/orchestrator#988]
build on macOS: 10.13.1
target OS: redhat 7.4

With the provided build.sh, I tried to build on my mac to a linux host using:
```
$./build.sh -t linux -a amd64
[DEBUG] Building via go version go1.12.6 darwin/amd64
# github.com/github/orchestrator/vendor/github.com/mattn/go-sqlite3
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:26:10: undefined: SQLiteConn
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:27:17: undefined: namedValue
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:29:13: undefined: namedValue
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:35:10: undefined: SQLiteConn
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:36:17: undefined: namedValue
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:44:10: undefined: SQLiteConn
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:49:10: undefined: SQLiteConn
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:54:10: undefined: SQLiteStmt
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:63:10: undefined: SQLiteStmt
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:36:17: too many errors
find: build/bin/orchestrator: No such file or directory
Failed to generate orchestrator binary
```

Followed instructions on sqlite3 [README about cross compiling](https://github.com/mattn/go-sqlite3/blob/master/README.md#cross-compile), I installed [cross gcc](http://crossgcc.rts-software.org/doku.php?id=compiling_for_linux), and prefixed `CGO_ENABLED=1 CC=/usr/local/gcc-4.8.1-for-linux64/bin/x86_64-pc-linux-gcc` to the `go build` command, which stopped the above error and build.sh exited successfully.
My default gcc info:
```
$gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

After copying the resulting rpm to the target linux host, Im getting error `rpm is intended for a different operating system` when installing. It seems fpm needs explicitly to be told the target os, with `--rpm-os linux`, so I added those to the build script and finally able to get it up running on the linug host.
fpm version: 1.11.0

Not sure if I missed something when building that the above steps are not necessary, if yes could you please let me know what it is so I can add to our docs?  Thanks

**Comment by shlomi-noach** [comment]
To build for Linux under MacOS, I advise (and should reflect that in the docs) to use the Docker builds. e.g. run 
- `docker build . -f Dockerfile -t orchestrator && docker run --rm -it -P 3000:3000 orchestrator:latest`
- `docker build . -f Dockerfile.packaging -t orchestrator-packaging && docker run --rm -it orchestrator-packaging:latest`

The first will build and run the `orchestrator` binary. The second will build distribution packages (`.deb`, `.rpm`) and place them in `/tmp/orchestrator-release` within the docker image.

**Comment by zhoumingmtv** [comment]
thanks for getting back, that helps.
